### ISSUE TITLE
In "go version go1.17.3 linux/amd64", The problem "Setctty set but Ctty not valid in child" appears again

### ISSUE THREAD

**Issue by 007xiaoxingxing** [creack/pty#134] opened 2021-11-16 17:51 UTC
go version go1.17.3 linux/amd64
write example code to main.go
```package main

import (
        "io"
        "os"
        "os/exec"
        "github.com/creack/pty"
)

func main() {
        c := exec.Command("grep", "--color=auto", "bar")
        f, err := pty.Start(c)
        if err != nil {
                panic(err)
        }

        go func() {
                f.Write([]byte("foo\n"))
                f.Write([]byte("bar\n"))
                f.Write([]byte("baz\n"))
                f.Write([]byte{4}) // EOT
        }()
        io.Copy(os.Stdout, f)
}
```

go.mod
```
go 1.17

require (
	github.com/creack/pty v1.1.7
	golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2
)

require golang.org/x/sys v0.0.0-20210423082822-04245dca01da // indirect
```

go run main.go
`panic: fork/exec /usr/bin/grep: Setctty set but Ctty not valid in child
goroutine 1 [running]:
main.main()`

I have been trying to debug this code,but have no idea how to solve this issue.I would appreciate it if you could give me some hint.
em.....I have find it out.When upgrade pty to v1.1.17,there is no problem at all.
I have learned a lot about terminal,Thanks for closing this issue.

**Comment by creack** [comment] 2022-01-31 13:48
I have not been able to reproduce with 1.17.3 nor with 1.18beta1. Could you provide more details on your setup?

Using the provided snippet, I end up with a different go.mod being generated, is the provided snippet the one resulting in an error?

Generated go.mod (1.17.3, go mod init test && go mod tidy) from the given snippet:

```
module a

go 1.17

require github.com/creack/pty v1.1.17
```

**Comment by creack** [comment] 2022-02-21 21:21
Closing as not reproducable.

If you do manage to find a way to reproduce, please feel free to re-open.

**Closed by creack** 2022-02-21 21:21 UTC

**Comment by af-afk** [comment] 2023-10-10 09:52
Hello, I've reproduced this with `go version go1.21.1 linux/amd64` with Debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux.

```
panic: failed to start pty: fork/exec /bin/sh: Setctty set but Ctty not valid in child
```

```go
// pty.go: reproduces a pty.go issue(?)

package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"

	"github.com/creack/pty"
)

func main() {
	cmd := exec.Command("/bin/sh")
	ptyCmd, err := pty.Start(cmd)
	if err != nil {
		panic(fmt.Sprintf("failed to start pty: %v", err))
	}
	defer ptyCmd.Close()
	if _, err := io.Copy(ptyCmd, os.Stdin); err != nil {
		panic(err)
	}
}
```

**Comment by jgillich** [comment] 2024-01-31 01:12
For some reason go likes to default to ancient versions, I added the import, ran `go mod tidy` and got pty v1.1.9. Very strange, updating fixed this issue for me

**Comment by aquarkgn** [comment] 2024-01-31 01:57
My version was v1.1.17 and I encountered the same issue. After upgrading the version in go.mod to v1.1.21, the problem was resolved. I hope this method is helpful to you.

```go
module terminal-x

go 1.19

require (
	// .......
	github.com/creack/pty v1.1.21
        // .......
)
``` `
