### ISSUE TITLE
undefined identifiers syscall.TIOCGPTN and syscall.TIOCSPTLCK (gollvm)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [creack/pty#104] opened 2020-09-16 16:41 UTC
Hello.
Create a cross-reference against [Undefined syscall.TIOCGPTN, syscall.TIOCSPTLCK during compilation of cri-o (gollvm related)](https://github.com/cri-o/cri-o/issues/4197) - I was trying to build [cri-o](https://cri-o.io/) using [gollvm](https://go.googlesource.com/gollvm/) .

Here is my environment:

> $go version
go version go1.15rc2 gollvm LLVM 12.0.0git linux/amd64

> $go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/oceanfish81/.cache/go-build"
GOENV="/home/oceanfish81/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/oceanfish81/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/oceanfish81/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/tools"
GCCGO="/usr/local/bin/llvm-goc"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/oceanfish81/cri-o/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build446537969=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

CC @paulzhol @kr @creack 
BCC @thanm @cherrymui 

Ivan

**Comment by creack** [comment] 2020-09-16 16:47
Thanks for the report. Does gollvm use specific build tags?

**Comment by cherrymui** [comment] 2020-09-16 18:24
Gollvm uses "gccgo" build tag. It work essentially the same as gccgo.

**Comment by creack** [comment] 2020-09-16 18:56
I couldn't reproduce the issue with gollvm and the pty lib. I'll see if I can dig into cri-o, but if you have a way to reproduce, it would be helpful.

For reference, here is what I did:

`cat Dockerfile`

```dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y git build-essential cmake m4 ninja-build

# Follow install instructions from https://go.googlesource.com/gollvm/

WORKDIR /workarea

RUN     git clone https://github.com/llvm/llvm-project.git

WORKDIR /workarea/llvm-project/llvm/tools
RUN     git clone https://go.googlesource.com/gollvm
WORKDIR /workarea/llvm-project/llvm/tools/gollvm
RUN     git clone https://go.googlesource.com/gofrontend
WORKDIR /workarea/llvm-project/llvm/tools/gollvm/libgo
RUN     git clone https://github.com/libffi/libffi.git
RUN     git clone https://github.com/ianlancetaylor/libbacktrace.git

RUN apt-get install -y python3

WORKDIR /workarea/build-debug
RUN     cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_USE_LINKER=gold -G Ninja ../llvm-project/llvm
RUN     ninja gollvm
RUN     ninja install-gollvm

ENV LD_LIBRARY_PATH=/workarea/build-debug/tools/gollvm/libgo

# Make sure the install worked.
RUN go version

# Use the snippet from the readme as test.
WORKDIR /app
ADD main.go .
RUN go mod init app && go get && go run main.go
```

`cat main.go`

```go
package main

import (
        "io"
        "os"
        "os/exec"

        "github.com/creack/pty"
)

func main() {
        c := exec.Command("grep", "--color=auto", "bar")
        f, err := pty.Start(c)
        if err != nil {
                panic(err)
        }

        go func() {
                f.Write([]byte("foo\n"))
                f.Write([]byte("bar\n"))
                f.Write([]byte("baz\n"))
                f.Write([]byte{4}) // EOT
        }()
        io.Copy(os.Stdout, f)
}
```

**Comment by advancedwebdeveloper** [comment] 2020-09-17 01:15
@creack , I see.
@thanm, I guess your patch would be helpful.

@fkautz ,
I think that is the first mentioned Dockerfile for building inside a container.

I am currently sticking to VMs - but will get to containers later.

**Comment by creack** [comment] 2020-09-17 01:38
I tried to reproduce using the commands provided on the cri-o issue, but still couldn't.
I checked the libgo archive and the syscall consts are indeed there. Could you check if they are present on your install?

```shell
root@ee70abd26c2d:/app/vendor/github.com/creack/pty# go version
go version go1.15rc2 gollvm LLVM 12.0.0git linux/amd64

root@ee70abd26c2d:/app/vendor/github.com/creack/pty# mkdir /b651
root@ee70abd26c2d:/app/vendor/github.com/creack/pty# /usr/local/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/creack/pty -o $WORK/b651/go.o -I $WORK/b651/importcfgroot ./doc.go ./ioctl.go ./pty_linux.go ./run.go ./util.go ./ztypes_amd64.go

root@ee70abd26c2d:/app/vendor/github.com/creack/pty# strings /usr/local/lib64/libgo.a | egrep 'TIOCGPTN|TIOCSPTLCK'
const TIOCGPTN = 2147767344
const TIOCSPTLCK = 1074025521
```

If you prefer VMs, this is fine too, would you have a Vagrantfile or a script I could use to reproduce?

As it seems more related to the build env than the pty lib, I am going to close the issue for now. If you think the issue is with the lib, please feel free to re-open.

**Closed by creack** 2020-09-17 01:38 UTC

**Comment by advancedwebdeveloper** [comment] 2020-09-19 08:51
> I tried to reproduce using the commands provided on the cri-o issue, but still couldn't.
> I checked the libgo archive and the syscall consts are indeed there. Could you check if they are present on your install?

@thanm seem to find some clues, on why I had those compiled-in bottlenecks. Waiting for a patch, in a meanwhile.
So let's just proceed once that would be done and everyone could re-build gollvm.

 
> If you prefer VMs, 
I am up to checking under(on?) any infrastructure and virt. approaches - I am just have poor understanding of CNCF's container technologies. But I am working under VMs for years - so I started with what I am good in.
Containers would be used later.

> this is fine too, would you have a Vagrantfile or a script I could use to reproduce?
I am not using Vagrant, yet - but I could offer scripts, that reproduce building gollvm and your project.
I am on Ubuntu 20 x86_64, on a bare metal. Also using WSL2 (Windows 10, on my host machine) [Ubuntu 20.04 LTS for WSL2](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab) .

> 
> As it seems more related to the build env than the pty lib, I am going to close the issue for now. If you think the issue is with the lib, please feel free to re-open.
Sure, let's check it later.
Thanks for your assistance.

**Comment by advancedwebdeveloper** [comment] 2020-09-23 14:11
@creack , @thanm : I just re-compiled gollvm - so here is my sub-folder:
[tools/gollvm/libgo](https://github.com/advancedwebdeveloper/gollvm_1.15.2_ubuntu20_release/tree/master/tools/gollvm/libgo
)
. No binaries or libraries featured, on Github - I am downloading compressed archives into Google Drive, right now.
I shall share the links.
Installation libraries (where you do not have to do 
> $sudo ninja install
) would be available from separate archives.
@thanm, please check whether auto-generated constants are presented (as expected).

I will re-build the pty package and report.
