### ISSUE TITLE
sample code runs into error: operation not supported by device

### ISSUE THREAD

**Issue by kcmvp** [creack/pty#185] opened 2024-01-13 14:31 UTC
here is the sample code from document

`// Set stdin in raw mode.
	**oldState, err := term.MakeRaw(int(os.Stdin.Fd()))**
	if err != nil {
		panic(err)
	}
	defer func() { _ = term.Restore(int(os.Stdin.Fd()), oldState) }() // Best effort.

	// Copy stdin to the pty and the pty to stdout.
	// NOTE: The goroutine will keep reading until the next keystroke before returning.
	go func() { _, _ = io.Copy(ptmx, os.Stdin) }()
	_, _ = io.Copy(os.Stdout, ptmx)
`

The bold line runs into error, the error mesage is 
`operation not supported by device`

here is the environment

mac os : 14.2.1
go version: 1.21.4
golang.org/x/term v0.16.0

**Comment by kcmvp** [comment] 2024-01-13 14:44
seems it's issue from term, I have raised a bug here
https://github.com/golang/go/issues/65095

**Comment by creack** [comment] 2024-01-13 14:55
I couldn't reproduce on osx 14.2.1 with go 1.21.4. Could you provide a more concrete example by any chance?

**Comment by aixintai** [comment] 2024-03-17 04:09
Same error, This is my test code:
```golang
func TestSyscallIOCTL(t *testing.T) {
	fd := os.Stdin 

	defer fd.Close()

	var value int
	_, _, errno := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd.Fd()), uintptr(0), uintptr(unsafe.Pointer(&value)))
	if errno != 0 {
		t.Errorf("Failed to get integer value: %s", errno)
		return
	}

	fmt.Println("Integer value:", value)
}
```
The output:
![CleanShot 2024-03-17 at 12 07 25@2x](https://github.com/creack/pty/assets/42685468/f943add6-8b01-436d-8ee6-b417c5fe1943)


 - MacBook Pro 2023(m3)  
 - uname: 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:54 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6031 arm64

**Comment by aixintai** [comment] 2024-03-21 03:19
the reason the test doesn’t wait for the interactive input is the Stdin of the process that’s executed (test binary), is set to the operating system’s null input device (/dev/null on [Unix](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/os/file_unix.go;l=202) and NUL on [Windows](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/os/file_windows.go;l=98)).  The DevNull device cannot set the raw mode or resize

**Comment by creack** [comment] 2024-03-21 03:35
That makes sense, but then there isn't much we can do, the library requires a valid tty device to work.

Closing for now, feel free to re-open if I missed something.

**Closed by creack** 2024-03-21 03:35 UTC
