### ISSUE TITLE
Unexpected behaviour when used with GDB --tty on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by cyrus-and** [creack/pty#29] opened 2015-04-28 15:53 UTC
First of all I want to apologise if the following is not an issue with this project, but I really don't know where to start.
### Issue

As the title says, I tried to use the terminals returned by `pty.Open()` to interact with the target program with GDB. I try to provide a minimal working example that reproduce this issue.

Here's a dummy C program (`hello.c`):

``` c
#include <stdio.h>

int main()
{
    printf("Hello!\n");
    return 0;
}
```

Here's the Go program (`issue.go`):

``` go
package main

import (
    "github.com/kr/pty"
    "io"
    "os"
    "os/exec"
)

func main() {
    ptm, pts, err := pty.Open()
    if err != nil {
        panic(err)
    }
    println(ptm.Name())
    println(pts.Name())

    ttyName := pts.Name()
    // ttyName := "/dev/ttys000" // taken from $ tty

    gdb := exec.Command("gdb", "--tty", ttyName)

    stdin, err := gdb.StdinPipe()
    if err != nil {
        panic(err)
    }

    if err := gdb.Start(); err != nil {
        panic(err)
    }

    go func() {
        _, err := io.Copy(os.Stdout, ptm)
        if err != nil {
            panic(err)
        }
    }()

    if _, err := stdin.Write([]byte("file ./a.out\n")); err != nil {
        panic(err)
    }

    if _, err := stdin.Write([]byte("run\n")); err != nil {
        panic(err)
    }

    // this is not received by GDB when ttyName := pts.Name()
    if _, err := stdin.Write([]byte("run\n")); err != nil {
        panic(err)
    }

    if _, err := stdin.Write([]byte("quit\n")); err != nil {
        panic(err)
    }

    if err := gdb.Wait(); err != nil {
        panic(err)
    }
}
```

Now with:

```
gcc hello.c
go run issue.go
```

what I get is:

```
/dev/ptmx
/dev/ttys001
Hello!
```

then the program is stuck. While if I use a TTY of another terminal as `ttyName` in `issue.go` everything seems to work as expected:

```
$ tty
/dev/ttys000
$ tail -f /dev/null
warning: GDB: Failed to set controlling terminal: Operation not permitted
Hello!
warning: GDB: Failed to set controlling terminal: Operation not permitted
Hello!
```

And the program exits successfully.

Also, commenting out the second `stdin.Write([]byte("run\n"))` the program works even with a TTY coming from `pty.Open()`.
### System details

```
$ uname -a
Darwin pacinotti-wifi-219-203.unipi.it 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
$ go version
go version go1.4.2 darwin/amd64
$ gdb --version
GNU gdb (GDB) 7.9
```

If more are needed please do ask.

**Comment by creack** [comment] 2015-04-28 16:09
What about something like this instead:

```go
package main

import (
        "io"
        "os"
        "os/exec"

        "github.com/kr/pty"
)

func main() {
        ptm, pts, err := pty.Open()
        if err != nil {
                panic(err)
        }
        println(ptm.Name())
        println(pts.Name())

        gdb := exec.Command("gdb")
        gdb.Stdin = pts
        gdb.Stdout = pts
        gdb.Stderr = pts
        if err := gdb.Start(); err != nil {
                panic(err)
        }
        go func() {
                _, err := io.Copy(os.Stdout, ptm)
                if err != nil {
                        panic(err)
                }
        }()
        stdin := ptm
        if _, err := stdin.Write([]byte("file ./a.out\n")); err != nil {
                panic(err)
        }
        if _, err := stdin.Write([]byte("run\n")); err != nil {
                panic(err)
        }
        // this is not received by GDB when ttyName := pts.Name()
        if _, err := stdin.Write([]byte("run\n")); err != nil {
                panic(err)
        }

        if _, err := stdin.Write([]byte("quit\n")); err != nil {
                panic(err)
        }
        if err := gdb.Wait(); err != nil {
                panic(err)
        }
}
```

**Comment by cyrus-and** [comment] 2015-04-28 16:18
Nope, the point of using the `--tty` option of GDB is to separate its own I/O from target program's.

**Comment by creack** [comment] 2015-04-28 17:51
What about this?

For some reason the `ptm` does not block and yields EOF upon each read. @kr any idea why?

Just keep going upon EOF allows for expected behavior.

```go
package main

import (
        "fmt"
        "io"
        "log"
        "os"
        "os/exec"

        "github.com/kr/pty"
)

func main() {
        ptm, pts, err := pty.Open()
        if err != nil {
                panic(err)
        }
        println(ptm.Name())
        println(pts.Name())

        ptsName := pts.Name()
        go func() {
                for {
                        buf := make([]byte, 1024)
                        n, err := ptm.Read(buf)
                        if err != nil {
                                if err != io.EOF {
                                        fmt.Printf("Err: %s\n", err)
                                        continue
                                }
                        }
                        if _, err := os.Stdout.Write(buf[:n]); err != nil {
                                log.Fatal(err)
                        }
                }
        }()

        gdb := exec.Command("gdb", "--tty", ptsName)
        // gdb.Stdout = os.Stdout
        // gdb.Stderr = os.Stderr

        stdin, err := gdb.StdinPipe()
        if err != nil {
                panic(err)
        }
        if err := gdb.Start(); err != nil {
                panic(err)
        }

        if _, err := stdin.Write([]byte("file ./a.out\n")); err != nil {
                panic(err)
        }

        if _, err := stdin.Write([]byte("run\n")); err != nil {
                panic(err)
        }
        // this is not received by GDB when ttyName := pts.Name()
        if _, err := stdin.Write([]byte("run\n")); err != nil {
                panic(err)
        }

        if _, err := stdin.Write([]byte("quit\n")); err != nil {
                panic(err)
        }

        if err := gdb.Wait(); err != nil {
                panic(err)
        }
}
```

**Comment by creack** [comment] 2015-04-28 17:57
I tried to manually set the non blocking mode via fcntl without luck, I tried to use `select(2)` without luck either.

**Comment by creack** [comment] 2015-04-28 18:02
ok, with this C code:

```C
#include <stdio.h>
#include <unistd.h>

int main()
{
  for (int i = 0; i < 10; i++) {
    printf("Hello!\n");
    sleep(1);
  }
  return 0;
}
```

I found out that the `ptm` is non blocking only when the `pts` is not used. Once `gdb` starts the process, `ptm` is blocking as expected.

**Comment by cyrus-and** [comment] 2015-04-28 19:20
Yes I can confirm that keep reading from `ptm` works:

```go
go func() {
	for {
		if _, err := io.Copy(os.Stdout, ptm); err != nil {
			panic(err)
		}
	}
}()
```

But I don't think it's a *solution*, isn't it?

I also noticed some others weird behaviours. Here I also copy the standard output of GDB to the main program's (`***`), the result is that the standard output of GDB is shown, while the output of the target program (from `ptm`) is not. Also in this case keep reading seems to fix; I report also this test case because, though related, it seems a different scenario.

```go
package main

import (
	"github.com/kr/pty"
	"io"
	"os"
	"os/exec"
)

func main() {
	ptm, pts, err := pty.Open()
	if err != nil {
		panic(err)
	}
	println(ptm.Name())
	println(pts.Name())

	ttyName := pts.Name()

	gdb := exec.Command("gdb", "--tty", ttyName)

	stdin, err := gdb.StdinPipe()
	if err != nil {
		panic(err)
	}

	// ***
	stdout, err := gdb.StdoutPipe()
	if err != nil {
		panic(err)
	}

	if err := gdb.Start(); err != nil {
		panic(err)
	}

	go func() {
		if _, err := io.Copy(os.Stdout, ptm); err != nil {
			panic(err)
		}
	}()

	// ***
	go func() {
		if _, err := io.Copy(os.Stdout, stdout); err != nil {
			panic(err)
		}
	}()

	if _, err := stdin.Write([]byte("file ./a.out\n")); err != nil {
		panic(err)
	}

	if _, err := stdin.Write([]byte("run\n")); err != nil {
		panic(err)
	}

	if _, err := stdin.Write([]byte("quit\n")); err != nil {
		panic(err)
	}

	if err := gdb.Wait(); err != nil {
		panic(err)
	}
}
```

**Comment by cyrus-and** [comment] 2015-04-29 09:56
Ok, it seems that the latter case is probably due to the fact that I don't close `ptm` and `pts` at the end; adding:

    ptm.Close()
    pts.Close()

after `gdb.Wait()` fixes.

Anyway, after this change, on Linux both examples I provided work.

**Comment by cyrus-and** [comment] 2015-05-07 17:56
**Update:** I published [the project](https://github.com/cyrus-and/gdb) in which I use the module `pty` and for which I opened this issue. If you have any suggestion please feel free to share your knowledge! :)

**Comment by creack** [comment] 2019-06-29 15:06
Closing as it the ticket is too old and seems to be solved. Feel to re-open if it is not the case.

**Closed by creack** 2019-06-29 15:06 UTC
