### ISSUE TITLE
Attempting to Read Bytes from PTY Results in "Invalid Argument"

### ISSUE THREAD

**Issue by incinerate-tools** [creack/pty#124] opened 2021-08-18 07:00 UTC
Attempting to run the following code snippet with the latest version of pty results in the this error: 
`Failed to read from pty master: invalid argument`

```
cmd := exec.Command("bash")
cmd.Env = append(os.Environ(), "TERM=xterm")
term, _ := pty.Start(cmd)

go func() {
  resBuf := make([]byte, 1024)
  for {
	  _, err := term.Read(resBuf)
	  if err != nil {
		  log.Printf("Failed to read from pty master: %s", err)
		  return
	  }
  }
}()

go func() {
  term.Write([]byte("t"))
  term.Write([]byte("o"))
  term.Write([]byte("p"))
  term.Write([]byte("\n"))
}()

time.Sleep(2 * time.Second)
```
The error results from the line `_, err := term.Read(resBuf)` which should work properly from what I have read in the repo examples as well as other projects, so I am not sure why this error is occurring.

My go version is `go1.17 linux/amd64`, and OS is `Ubuntu 18.04.4 LTS`.

**Comment by creack** [comment] 2021-08-18 11:57
I can't reproduce the issue with `go version go1.17 linux/amd64` on `Ubuntu 20.10 (Groovy Gorilla)`.

Could you provide a full example (including main).

**Comment by creack** [comment] 2021-09-27 16:23
Closing as idle, I'll assume it is fixed :) Please feel free to re-open if you still have the issue.

**Closed by creack** 2021-09-27 16:23 UTC
