### ISSUE TITLE
No color on Linux?

### ISSUE THREAD

**Issue by dpacbach** [creack/pty#112] opened 2021-03-23 00:42 UTC
Hi, I am using a program called lazygit ([github](http://github.com/jesseduffield/lazygit)) which uses the pty module.  I am running Linux, on various Debian/Ubuntu-based flavors.  I am having an issue where the output of the pty module seems to remove color.  I raised an issue in the jesseduffield/lazygit repo [here](https://github.com/jesseduffield/lazygit/issues/1138).  That program basically uses the pty module to run a command and display the output in a terminal UI.  Any color emitted by the command is supposed to be preserved, but on my system for some reason it seems that it's being removed.  Would it be possible to take a brief look at the issue mentioned above to help us diagnose?  The place where it uses the pty module is here:

https://github.com/jesseduffield/lazygit/blob/master/pkg/gui/pty.go

Any help would be appreciated!

**Comment by creack** [comment] 2021-03-24 12:03
I'll see what I can do, but I am a bit backed up with issues/PRs.

Colors are not related to the pty, they are just ANSI escape sequence and supports up to 24bit depth "truecolor". The limiting factor is the terminate emulator and how it interprets those escape sequences and displays them.

You might want to look elsewhere in the meantime as I strongly doubt the issue is coming from this lib.

Might want to check your Terminal color support with this script https://github.com/creack/dotfiles/blob/master/truecolor-test.sh and/or termcaps in general https://github.com/creack/dotfiles/blob/master/termcap-test.sh.

For reference, on iTerm (osx), it looks like this:
![image](https://user-images.githubusercontent.com/521701/112307216-10748280-8c77-11eb-80a1-f6ba0eb9c2bb.png)

Similar look using Putty on windows and if properly setup, most Linux terminal emulators should look at least like this if not better.

**Comment by dpacbach** [comment] 2021-03-25 00:26
@creack thanks for the reply!

**Comment by krader1961** [comment] 2021-04-29 00:44
@dpacbach: It is a certainty the problem is not due to to the pty package. There are many possible reasons why the program you are running is not coloring its output. For example, the program's stdin or stdout may not be attached to the pty you created. Or, you are running the program with a flag, env var, or other config option that inhibits coloring the output. Also, have you actually confirmed that `gui.GitCommand.GetPager(width)` is returning a non-empty string and that its value is correct?

**Comment by creack** [comment] 2021-05-29 17:58
Closing as it is not related to the lib. Sorry I can't be more helpful.

**Closed by creack** 2021-05-29 17:58 UTC
