### ISSUE TITLE
GOOS=windows build on linux  undefined: pty.Start

### ISSUE THREAD

**Issue by mamh2021** [creack/pty#158] opened 2022-09-16 09:40 UTC

**Comment by photostorm** [comment] 2022-09-16 12:07
Windows is currently not supported in the master branch

**Comment by creack** [comment] 2023-10-26 14:30
sorry for the delay. @mamh2021 couldyou provide more details and maybe an example to reproduce?

While Windows is indeed not supported yet (very soon to be), it should still be able to compile.

I did just find a similar issue, but with syscall.SIGWINCH, not with pty.Start.

**Comment by creack** [comment] 2023-11-09 15:36
Closing as can't reproduce. Likely fixed in a recent version.

**Closed by creack** 2023-11-09 15:36 UTC
Labels: windows, os-arch-port
