### ISSUE TITLE
reference to undefined identifier 'syscall.TIOCGPTN', 'syscall.TIOCSPTLCK'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [creack/pty#107] opened 2020-10-25 12:03 UTC
Hello.
I couldn't build your package.

> $ go get github.com/creack/pty
> go: downloading github.com/creack/pty v1.1.11
> go: github.com/creack/pty upgrade => v1.1.11
> \# github.com/creack/pty
> ../go/pkg/mod/github.com/creack/pty@v1.1.11/pty_linux.go:40:31: error: reference to undefined identifier 'syscall.TIOCGPTN'
> ../go/pkg/mod/github.com/creack/pty@v1.1.11/pty_linux.go:50:31: error: reference to undefined identifier 'syscall.TIOCSPTLCK'
> 

I am using 

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64
and here is my environment:

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/survey/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build857733618=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by creack** [comment] 2020-10-25 15:08
Closing as dup of #104. Couldn't reproduce from a fresh ubuntu install following the gollvm install instructions from https://go.googlesource.com/gollvm/

**Closed by creack** 2020-10-25 15:08 UTC
