### ISSUE TITLE
read /dev/ptmx: input/output error

### ISSUE THREAD

**Issue by horsley** [creack/pty#21] opened 2014-03-28 12:11 UTC
It's doesn't exist  /dev/ptmx but /dev/pts/ptmx
so I can make a soft link?
or change the path hardcode in pty_linux.go?

**Comment by jeremyschlatter** [comment] 2015-08-10 02:28
@paulzhol @keithpitt 

I can reproduce this issue with the README example and the Docker golang container:

```
$ tree
.
├── Dockerfile
└── example.go

0 directories, 2 files
```

Dockerfile:

```
FROM golang:onbuild
```

example.go (same as example, but printing the error from io.Copy):

```go
package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"

	"github.com/kr/pty"
)

func main() {
	c := exec.Command("grep", "--color=auto", "bar")
	f, err := pty.Start(c)
	if err != nil {
		panic(err)
	}

	go func() {
		f.Write([]byte("foo\n"))
		f.Write([]byte("bar\n"))
		f.Write([]byte("baz\n"))
		f.Write([]byte{4}) // EOT
	}()
	_, err = io.Copy(os.Stdout, f)
	fmt.Println(err)
}
```

Building and running:

```
$ docker build -t repro .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon
Step 0 : FROM golang:onbuild
# Executing 3 build triggers
Trigger 0, COPY . /go/src/app
Step 0 : COPY . /go/src/app
 ---> Using cache
Trigger 1, RUN go-wrapper download
Step 0 : RUN go-wrapper download
 ---> Using cache
Trigger 2, RUN go-wrapper install
Step 0 : RUN go-wrapper install
 ---> Using cache
 ---> dd1f1a9f24a7
Successfully built dd1f1a9f24a7
```

```
$ docker run repro
+ exec app
foo
bar
baz
bar
read /dev/ptmx: input/output error
```

It looks like the problem is that when the subcommand exits, reading from the pty file returns an I/O error rather than EOF.

**Comment by paulzhol** [comment] 2015-08-10 09:36
I think the Linux kernel is returning EIO when attempting to read from a master pseudo terminal which  no longer has an open slave.
https://github.com/torvalds/linux/blob/master/drivers/tty/tty_io.c#L1049
https://github.com/torvalds/linux/blob/master/drivers/tty/n_tty.c#L2194

**Comment by purpleidea** [comment] 2016-06-08 05:02
I just hit this issue on Fedora 23. The issue is that /dev/ptmx doesn't exist. On fedora it's called /dev/pts/ptmx so we need to detect for the OS and switch accordingly.

**Comment by paulzhol** [comment] 2016-06-08 07:42
@purpleidea Do you know if your kernel has this patch https://lwn.net/Articles/689539 ?
>All mounts of the devpts filesystem now create a /dev/pts/ptmx node
>with permissions 0000.

If so, can you try to create the /dev/ptmx device `mknod /dev/ptmx c 5 2`?

>To retain backwards compatibility the a ptmx device node (aka any node
>created with "mknod name c 5 2") when opened will look for an instance
>of devpts under the name "pts" in the same directory as the ptmx device
>node.

See [devpts](https://www.kernel.org/doc/Documentation/filesystems/devpts.txt)

**Comment by purpleidea** [comment] 2016-06-08 08:38
On closer inspection:

```
$ ll /dev/ptmx 
crw-rw-rw-. 1 root 5, 2 Jun  8 04:37 /dev/ptmx
$ ll /dev/pts/ptmx 
c---------. 1 root 5, 2 May 29 05:57 /dev/pts/ptmx
```

Weird, did a device get created when I wasn't looking? Gah...

**Comment by ls0f** [comment] 2018-05-25 12:28
the same question on centos 

`ll /dev/ptmx` get `crw-rw-rw- 1 root tty 5, 2 May 25 20:27 /dev/ptmx`

**Comment by F21** [comment] 2019-07-18 23:36
Recent https://github.com/unchartedsoftware/witch upgraded from `1.1.2` to `1.1.7` and I am now seeing this problem.

The environment is the latest Golang 1.2-alpine container. I can also see that `/dev/ptmx` exists in the container.

**Comment by creack** [comment] 2019-07-18 23:39
Would you have a sample code / dockerfile to reproduce the issue by anychance? Afk atm, but will take a look asap.

**Comment by F21** [comment] 2019-07-18 23:50
@creack I've pushed sample docker-compose files to reproduce this. See https://github.com/F21/ptytest

**Comment by creack** [comment] 2019-07-19 02:49
@F21 Thank you so much for the docker sample, it is very helpful.

Unfortunately, it seems like it is an "issue" with `witch` and not `pty`. I don't have enough time to dig too much in-depth, but consider the following dockerfile:

```
FROM golang:1.12-alpine

RUN apk --no-cache --no-progress add git

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get github.com/unchartedsoftware/witch
WORKDIR /go/src/github.com/unchartedsoftware/witch

# Master fails, but this commit works, using the same pty lib version.
RUN git checkout 33a995176f45a86ef9c4a2a02664650c80f5d231 && sed -i -e 's|kr/pty|creack/pty|' main.go
RUN dep ensure && dep status

RUN go install

CMD witch --cmd="echo hello" --watch="*.mod,**/*.go"
```

Using the working commit from `witch` you provided and patching it to use `creack/pty` v1.1.7, it does work as expected.

Note that the error is actually not an issue, it could (and should) be ignored. The child's side of the pty being closed when the child dies, the subsequent read on ptmx is expected to fail. It could be worked around by setting the pty only on the parent and passing a system pipe to the child (not 100% sure, would need to test), but seems like a big overhead for not much. Just like `http.ListenAndServe` always returns an error, you can consider that the ptmx read will also always return an error. If using a system pipe, then the pipe read would fail too.

**Comment by F21** [comment] 2019-07-19 02:52
Thank you so much for looking into this @creack and sorry for the noise. I'll point the maintainers of witch to your comment.

**Comment by jingweno** [comment] 2020-01-05 07:49
I just ran into this issue with Ubuntu 19.10. Does anyone have a fix for this? Thanks!

**Comment by fideloper** [comment] 2020-06-07 02:20
So to confirm, it sounds like `read /dev/ptmx: input/output error` is an expected error we can ignore?

I also sometimes see error `read /dev/ptmx: file already closed`, **and I'm not sure if I'm doing something incorrect there to get this error.**

Here's a relatively simple example on Go1.14. Ubuntu 18.04, and and Docker containers (Docker Desktop on my Mac and within Ubuntu linux) seem to have this output. I can't reproduce it on Mac Catalina. 

> The following assumes a `run.sh` script exists in CWD and does some stuff that takes a few second and has output. In my case, I run `composer install` for a faux-php project.

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"os/exec"

	"github.com/creack/pty"
)

func main() {
	cmd := exec.Command("/bin/bash", "run.sh")
	tty, err := pty.Start(cmd)

	if err != nil {
		panic(err)
	}

	defer tty.Close()

	var bytes []byte

	go func() {
		buf := bufio.NewReader(tty)

		for {
			byte, err := buf.ReadByte()
			bytes = append(bytes, byte)

			if err == io.EOF {
				fmt.Printf("io.EOF error: Bytes in this cycle: '%s'\n", string(byte))
				break
			}

			if err != nil {
				fmt.Printf("We have an error: %v\n", err)
			}
		}
	}()

	res := cmd.Wait()

	fmt.Printf("Result: '%v'\n", res)
	fmt.Printf("%s", string(bytes))
}
```

The errors and order of output isn't consistent so I assume it's based on the timing of when Go is doing certain operations?

**Comment by creack** [comment] 2020-06-22 16:48
Seems there are actually multiple different issues here, some which have been fixed. I'm going to close as the ticket as been going on since 2014 and is mainly outdated noise at this point.

If anyone still has the issue, please open a new ticket and we'll make sure to get it fixed.

cc @rbUUbr I didn't spend too much time on this but couldn't reproduce the issue.

cc @fideloper sorry for the delayed answer, if you are still facing the issue, please open a new issue.

**Closed by creack** 2020-06-22 16:48 UTC
