### ISSUE TITLE
error on go test create coverage report

### ISSUE THREAD

**Issue by shaheerkootteeri** [creack/pty#166] opened 2023-02-22 19:59 UTC
I am using pty terminal to display and validate my output in my project. When I upgrade the go version to 1.20.1 and re-run the tests with coverage as below in github actions, fails with error  `error generating coverage report: write /dev/pts/1: file already closed` 

`go test -v -timeout 10m -covermode=atomic -coverprofile=coverage.txt .......`

There were no issues running this in go version 1.19.

We are using creack/pty version:  v1.1.18

go version go1.20.1 darwin/amd64

**Comment by creack** [comment] 2023-10-26 15:41
Would you have a way to reproduce? Unfortunately, I haven't been able to.

**Comment by creack** [comment] 2023-11-16 15:33
Closing as can't reproduce.

**Closed by creack** 2023-11-16 15:33 UTC
